# Generated by Django 5.2.4 on 2025-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('book', 'Book'), ('home', 'Home'), ('cosmetics', 'Cosmetics'), ('accessories', 'Accessories'), ('kitchen', 'Kitchen'), ('furniture', 'Furniture')], default='home', max_length=50),
        ),
    ]
